# Generated by Django 5.0.4 on 2024-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proyecto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tema',
            field=models.CharField(choices=[('0', 'Economía'), ('1', 'Educación'), ('2', 'Social'), ('3', 'Ciencias'), ('4', 'Ecológico'), ('5', 'Innovación')], max_length=100, verbose_name='Tema'),
        ),
    ]
