# Generated by Django 5.0.4 on 2024-06-03 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proyecto_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profesor'),
        ),
    ]
